FROM node:22-bookworm-slim

WORKDIR /app

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
  && apt-get install -y --no-install-recommends openssl ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages

RUN npm ci
RUN npm run prisma:generate -w @yourpassenger/auth-service \
  && npm run prisma:generate -w @yourpassenger/profile-service \
  && npm run prisma:generate -w @yourpassenger/session-service \
  && npm run build

CMD ["npm", "run", "start", "-w", "@yourpassenger/app-server"]
